# Generated by Django 6.0.5 on 2026-05-11 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_trainer_alter_pokemon_height_alter_pokemon_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.trainer'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('L', 'Lagartija'), ('P', 'Planta'), ('E', 'Eléctrico'), ('T', 'Tierra'), ('A', 'Agua'), ('F', 'Fuego')], max_length=30),
        ),
    ]
