# Generated by Django 6.0.5 on 2026-06-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_pokemon_picture_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('E', 'Eléctrico'), ('F', 'Fuego'), ('L', 'Lagartija'), ('P', 'Planta'), ('T', 'Tierra'), ('A', 'Agua')], max_length=30),
        ),
    ]
